### Variables
@base_url       = http://localhost:8081
@version        = v6.0.0
@api_base       = {{base_url}}/obp/{{version}}
@admin_username = admin@example.com
@admin_password = admin123
@consumer_key   = vyyecfb35jy1xa302w4vvafhkngor3fses3dr1dl

### 🔍 Validate OBP is running
GET {{api_base}}/root

### Get the API tags, this just metadat that explains the groupings of api that are deployde in hte sandbox
GET {{api_base}}/tags

### test
GET {{api_base}}/well-known

### 1️⃣ DirectLogin - Get Token
POST {{api_base}}/my/logins/direct
Authorization: DirectLogin username={{admin_username}},password={{admin_password}},consumer_key={{consumer_key}}
Content-Type: application/json

{}

> {%
  client.global.set("token", response.body.token);
%}

### 2️⃣ Create a Consumer
POST {{api_base}}/management/consumers
Authorization: DirectLogin token={{token}}
Content-Type: application/json

{
  "name": "intellij-consumer",
  "app_type": "web",
  "description": "Created via IntelliJ HTTP Client",
  "developer_email": "{{admin_username}}",
  "redirect_url": "https://localhost/callback"
}

> {%
  client.global.set("consumer_key", response.body.consumer_key);
  client.global.set("consumer_id", response.body.consumer_id);
%}


### 3️⃣ List all Consumers
GET {{api_base}}/management/consumers
Authorization: DirectLogin token={{token}}


### 🆕 Bootstrap: DirectLogin With Dummy Consumer Key
# OBP_DIRECT_LOGIN_CONSUMER_KEY_MANDATORY=false means the consumer_key won't be validated
# So we can use any dummy value - it just needs to be present in the request
POST {{api_base}}/my/logins/direct
Authorization: DirectLogin username={{admin_username}},password={{admin_password}},consumer_key=dummy
Content-Type: application/json

{}

> {%
  client.global.set("bootstrap_token", response.body.token);
%}


### 🆕 Bootstrap: Create First Consumer (Using Bootstrap Token)
# Use the token from above to programmatically create your first consumer
POST {{api_base}}/management/consumers
Authorization: DirectLogin token={{bootstrap_token}}
Content-Type: application/json

{
  "name": "bootstrap-consumer",
  "app_type": "web",
  "description": "First consumer created programmatically without GUI",
  "developer_email": "{{admin_username}}",
  "redirect_url": "https://localhost/callback"
}

> {%
  client.global.set("new_consumer_key", response.body.consumer_key);
  client.global.set("new_consumer_secret", response.body.consumer_secret);
%}
