spring:
  application:
    name: identity-broker

server:
  port: 9000

identity-broker:
  issuer-uri: http://localhost:9000
  default-audiences:
    - http://localhost:9091
    - money-mate-api-token-exchange
  token-exchange-client:
    client-id: money-mate-api-token-exchange
    client-secret: money-mate-api-token-exchange-secret
  intellij-http-client:
    client-id: intellij-http-client
    redirect-uri: http://127.0.0.1:63342/api/http-client/oauth2/callback
  demo-users:
    - username: katja.fi.29@example.com
      password: ca0317
    - username: timo.fi.29@example.com
      password: 6addcd
    - username: ellie.de.29@example.com
      password: 2efb1f

obp:
  api:
    base-url: https://apisandbox.openbankproject.com
    connect-timeout: 10s
    read-timeout: 30s
  auth:
    consumer-key: fxkjmwyvdvavauhk2pauycrtxjofjh5ksayqk150
