spring:
  application:
    name: identity-broker

server:
  port: 9000

identity-broker:
  issuer-uri: http://localhost:9000
  default-audience: http://localhost:9091
  test-user:
    username: demo
    password: demo
