spring:
  application:
    name: http-session-mcp
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          audiences:
            - http://localhost:9091
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: http-session-mcp
        version: 1.0.0
        type: SYNC
        streamable-http:
          mcp-endpoint: /mcp
        annotation-scanner:
          enabled: true

server:
  port: 9091

http-session-mcp:
  authorization-server: http://localhost:9000
